server:
  port: 80 #HTTP协议默认80端口，因此只需要输入网址就行，给测试或用户也不应该让他们输入端口号


spring:
  application:
    name: cloud-payment-consumer
  cloud:
    zookeeper:
      connect-string: 47.94.23.231:2181

#eureka:
#  client:
#    #表示将自己注册进注册中心
#    register-with-eureka: true
#    #是否从EurekaServer中抓取已有的注册信息，默认为true。单点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetch-registry: true
#    service-url:
#      #单机版
##      defaultZone: http://localhost:7001/eureka
#
#      #集群版
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#  instance:
#    instance-id: consumer80
#    prefer-ip-address: true