server:
  port: 8004
spring:
  application:
    name: cloud-provider-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.94.23.231:3306/local?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 12345678
  cloud:
    zookeeper:
      connect-string: 47.94.23.231:2181

#
#eureka:
#  client:
#    #表示将自己注册进注册中心
#    register-with-eureka: true
#    #是否从EurekaServer中抓取已有的注册信息，默认为true。单点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetch-registry: true
#    service-url:
#      #单机版 defaultZone: http://localhost:7001/eureka
#
#      #集群版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka，
#
#  instance:
#    #修改eureka主机名
#    instance-id: payment8002
#    #访问路径可以显示ip地址
#    prefer-ip-address: true
#    #Eureka客户端向服务端发送心跳的时间间隔，默认30s
#    lease-renewal-interval-in-seconds: 1
#    #Eureka服务端在接收到最后一次心跳后等待时间上限，默认是90秒
#    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springcloud.demo.entity